bytes str 오류
TypeError: a bytes-like object is required, not 'str' 

오류가 발생하기에 수정 후 재실행해보니 

Received b'N\x00\x00\x00...' 출력 확인